image:
  repository: thedevopsdude/complete-devops-project
  tag: ce8829a    # Added space after the colon
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false