image:
  repository: thedevopsdude/complete-devops-project
  tag:71464c9 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount: 
  enabled: false

autoscaling:
  enabled: false  