image:
  repository: hirudoc5/complete-devops-project
  tag:2f6a7b6 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false